### PR TITLE
35821 - added custom env variable for URI path

### PR DESCRIPTION
**Pull request by LiudmylaMasliuk**

### CODE REVIEW

**Comment by Roypoe** [comment]
Hi @LiudmylaMasliuk @mbe1987, when do you think will you be able to proceed with this one? Thanks in advance

**Review by mbe1987 — APPROVED** [review]

**Comment by Roypoe** [comment]
@LiudmylaMasliuk Do you plan to add a release tag or should we just use it?

**Comment by LiudmylaMasliuk** [comment]
@Roypoe we will make new release as soon as we get previous certification results from commercetools (hopefully from previous experience it will happen within next few days, unfortunately it is not possible to trigger new one before previous is finished). For now the implementation can already run locally.

**Comment by Roypoe** [comment]
@LiudmylaMasliuk Thank you

**Pull request merged**
